# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Matrix'
description: 'Generate a matrix from a Bake definition to help distributing builds in your workflow'

inputs:
  workdir:
    description: Working directory
    default: '.'
    required: false
  files:
    description: List of Bake files
    required: false
  target:
    description: Bake target
    required: false
  fields:
    description: Comma separated list of extra fields to include in the matrix
    required: false

outputs:
  matrix:
    description: List of includes as matrix
    value: ${{ steps.generate.outputs.includes }}

runs:
  using: composite
  steps:
    -
      name: Generate
      id: generate
      uses: actions/github-script@v7
      with:
        script: |
          let def;
          const files = `${{ inputs.files }}` ? `${{ inputs.files }}`.split('\n') : [];
          const target = `${{ inputs.target }}`;
          const fields = `${{ inputs.fields }}` ? `${{ inputs.fields }}`.split(',') : [];

          await core.group(`Parsing definition`, async () => {
            let args = ['buildx', 'bake'];
            for (const file of files) {
              args.push('--file', file);
            }
            if (target) {
              args.push(target);
            }
            args.push('--print');

            const res = await exec.getExecOutput('docker', args, {
              ignoreReturnCode: true,
              silent: true,
              cwd: `${{ inputs.workdir }}`
            });
            if (res.stderr.length > 0 && res.exitCode != 0) {
              throw new Error(res.stderr);
            }
            def = JSON.parse(res.stdout.trim());
            core.info(JSON.stringify(def, null, 2));
          });

          await core.group(`Generating matrix`, async () => {
            const result = [];
            for (const targetName of Object.keys(def.target)) {
              const target = def.target[targetName];
              const entry = { target: targetName };
              Object.keys(target).forEach(field => {
                if (fields.includes(field)) {
                  const value = target[field];
                  if (Array.isArray(value)) {
                    value.forEach((v: string) => {
                      entry[field] = v
                      result.push({ ...entry });
                    });
                  } else {
                      entry[field] = value;
                      result.push({ ...entry });
                  }
                }
              });
            }
            core.info(JSON.stringify(result, null, 2));
            core.setOutput('includes', JSON.stringify(result));
          });
